# Generated by Django 5.2.17 on 2026-08-10 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Payment Verification'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='special_request',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
