# Generated by Django 5.2.17 on 2026-08-11 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_reservation_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMapPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('y', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('width', models.DecimalField(decimal_places=3, default=8, max_digits=6)),
                ('height', models.DecimalField(decimal_places=3, default=6, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_position', to='core.room')),
            ],
        ),
    ]
