# Generated by Django 5.2.17 on 2026-08-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_roommapposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommapposition',
            name='rotation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='roommapposition',
            name='z_index',
            field=models.IntegerField(default=1),
        ),
    ]
