# Generated by Django 5.2.17 on 2026-08-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_roommapposition_rotation_roommapposition_z_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommapposition',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='roommapposition',
            name='z_index',
        ),
        migrations.AddField(
            model_name='roommapposition',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
